spring:
  application:
    name: RankStream Internal API
    version: 0.0.1-SNAPSHOT
---
spring:
  profiles:
    group:
      local: local-api, local-db, common-logging
---
spring:
  config:
    activate:
      on-profile: local-api
cors:
  origins: http://localhost:3000
  methods: "*"
  headers: "*"
jwt:
  secret: TestJwtKey
  issuer: RankStream
---
spring:
  config:
    activate:
      on-profile: local-db
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: needmoney
      jdbc-url: jdbc:mariadb://localhost:3306/rankstream
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
